[project]
name = "diamond-viewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-python-headless>=4.13.0.92",
    "pdfplumber>=0.11.9",
    "playwright>=1.58.0",
    "requests>=2.31.0",
]
